mysite/mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
  #  url(r'^bsp/net/',include('netIITD.urls')),
   url(r'^net/',include('netIITD.urls')),
#    url(r'^',include('netIITD.urls')),
    url(r'^admin/', admin.site.urls),
]

mysite/netIITD/urls.py
from django.conf.urls import url
from . import views

app_name='netIITD'
urlpatterns = [
	url(r'^$',views.index),	
	url(r'showall',views.showall),
	url(r'tp',views.tp),
	url(r'comtrans',views.addComTrans,name='comtrans'),
	url(r'prodreq',views.addProdReq,name='prodreq'),
	url(r'prodhpur',views.purProdHouse,name='prodhpur'),
	url(r'purbankveto',views.purBankVeto,name='purbankveto'),
	url(r'bankloan',views.BankLoan,name='bankloan'),
	url(r'payback',views.Payback,name='payback'),
	url(r'retgov',views.RetGov,name='retgov'),
	url(r'savedata',views.SaveData,name='savedata'),
	url(r'reset',views.Reset,name='reset'),
	url(r'relate',views.Relate,name='relate'),
	url(r'restart',views.Restart,name='restart'),
]

mysite/netIITD/models.py
from django.db import models

# Create your models here.

class Material(models.Model):
	material_name = models.CharField(max_length=50)
	base_price = models.FloatField(default=1000)
	def __str__(self):
		return self.material_name

class Company(models.Model):
	com_name = models.CharField(max_length=50)
	com_type = models.ForeignKey(Material,on_delete=models.CASCADE)
	com_money = models.FloatField(default=20000.0)
	prod_units = models.IntegerField(default=0)
	
	def __str__(self):
		return self.com_name

class ComMat(models.Model):
	com = models.ForeignKey(Company)
	mat = models.ForeignKey(Material)
	amt = models.FloatField(default=10)

	def __str__(self):
		return (self.com.com_name + " -> " + self.mat.material_name)

class Nation(models.Model):
	nation_name = models.CharField(max_length=50)
	nation_money = models.FloatField(default=100000)
	prod_units = models.IntegerField(default=3)

	def __str__(self):
		return self.nation_name

class Bank(models.Model):
	bank_name = models.CharField(max_length=50)
	bank_money = models.FloatField(default=600000)
	veto = models.FloatField(default=100)
	
	def __str__(self):
		return self.bank_name

class BankNation(models.Model):
	nation = models.ForeignKey(Nation)
	bank = models.ForeignKey(Bank)
	veto_part = models.FloatField(default=0)

	def __str__(self):
		return (self.nation.nation_name+" - "+self.bank.bank_name)

class LoanTrans(models.Model):
	com = models.ForeignKey(Company)
	bank = models.ForeignKey(Bank)
	ret = models.FloatField(default=0)
	
	def __str__(self):
		return (self.bank.bank_name+" - "+self.com.com_name)	


class ProdReq(models.Model):
	com = models.ForeignKey(Company)
	out = models.ForeignKey(Material)
	prod_units = models.IntegerField()
	tim = models.DateTimeField(auto_now = True)

	def __str__(self):
		return self.com.com_name+" -> "+self.out.material_name


class ProdTrans(models.Model):
	com1 = models.ForeignKey(Company,related_name='c1')
	com2 = models.ForeignKey(Company,related_name='c2')
	prod_type = models.ForeignKey(Material,on_delete=models.CASCADE)
	price_per_unit = models.FloatField(default=1)
	prod_units = models.IntegerField()

	def __str__(self):
		return self.com1.com_name+" - "+self.com2.com_name+" : "+self.prod_type.material_name

class PurProdHouse(models.Model):
	com = models.ForeignKey(Company)
	nation = models.ForeignKey(Nation)
	prod_units = models.IntegerField()

	def __str__(self):
		return self.com.com_name+" - "+self.nation.nation_name+" : "+self.prod_units

class PurBankVeto(models.Model):
	nation = models.ForeignKey(Nation)
	bank = models.ForeignKey(Bank)
	veto = models.FloatField()
	price = models.FloatField()

mysite/netIITD/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.template import loader

from django.http import StreamingHttpResponse
from django.views.static import serve

import subprocess
import os
import math
import threading
import time
import pdb
from .models import Company,Nation,Bank,ProdTrans,Material,ProdReq,BankNation,LoanTrans,ComMat,PurProdHouse,PurProdHouse


# Create your views here.
def index(request):	
	return HttpResponse("Add data through admin page and then call visit /net/relate to populate the related db")

def Relate(request):
	companies = Company.objects.all().order_by("pk")
	nations = Nation.objects.all().order_by("pk")
	banks = Bank.objects.all().order_by("pk")
	materials = Material.objects.all().order_by("pk")
	for n in nations:
		for b in banks:
			if BankNation.objects.filter(nation=n, bank=b).exists():
				a=1
			else:
				bn = BankNation(nation=n,bank=b,veto_part=0)
				bn.save()

	for c in companies:
		for m in materials:
			if ComMat.objects.filter(com=c, mat=m).exists():	
				b=1
			else:
				if c.com_type.id == m.id:
					cm = ComMat(com=c,mat=m,amt=30.0)
					cm.save()
				else:
					cm = ComMat(com=c,mat=m,amt=0.0)
					cm.save()
	return redirect('/bsp/net/showall')
	#return showall(request)

def tp(request):
	context={}
	return render(request,'netIITD/tp.html',context)

def showall(request):
	companies = Company.objects.all().order_by("pk")
	commats = ComMat.objects.all().order_by("com_id","mat_id")			# to represent amt of material each company has
	nations = Nation.objects.all().order_by("pk")
	banks = Bank.objects.all().order_by("pk")
	materials = Material.objects.all().order_by("pk")
	banknations = BankNation.objects.all().order_by("nation_id","bank_id")	# to represent veto power of each bank a nation has
	matNo = len(materials)
	mx = []
	for i in range(1,matNo+1):
		tmp = []
		for j in range(0,4):
			tmp.append(materials[(i-j)%matNo]) 
		mx.append(tmp)
	template = loader.get_template('netIITD/index.html')
	context = { 'companies':companies, 'nations':nations,'banks':banks, 'materials':materials,'banknations':banknations,'bankNo':range(1,100), 'commats':commats,'mx':mx}
	return render(request,'netIITD/index.html',context)

def addComTrans(request):
	subsidy= 1.4
	try:
		#pdb.set_trace()
		c1=Company.objects.get(pk=request.POST['c1'])
		c2=Company.objects.get(pk=request.POST['c2'])
		mat_id=int(request.POST['mat'])
		mat=Material.objects.get(pk=mat_id)
		units=int(request.POST['units'])
		ppu=float(request.POST['ppu'])
		moneyEx = ppu*units
		c1Mat = ComMat.objects.get(com=c1,mat=mat)
		c2Mat = ComMat.objects.get(com=c2,mat=mat)
		if(c1.id==c2.id or ppu<0 or units<0 or c1Mat.amt<units or c2.com_money< moneyEx):
			return HttpResponse("Inputs don't make sense! Go back and change things properly.")
	except (KeyError, Company.DoesNotExist):
		return render(request,'netIITD/index.html',{'error_message':'Selected Choice does not exist',})
	else:
		c1Mat.amt = c1Mat.amt - units
		c2.com_money = c2.com_money -  moneyEx
		tmpid = c2.com_type.id
		if(c1.com_type.id==mat_id and ((tmpid-1)%7== (mat_id)%7 or (tmpid-2)%7== mat_id%7 or (tmpid-3)%7== mat_id%7)):
			moneyEx = moneyEx*subsidy
		c1.com_money = c1.com_money + moneyEx
		c2Mat.amt = c2Mat.amt + units
		pt = ProdTrans(com1=c1,com2=c2,prod_type=mat,price_per_unit=ppu,prod_units=units)
		pt.save()
		c1.save()
		c2.save()
		c1Mat.save()
		c2Mat.save()
	return redirect('/bsp/net/showall')

def prodDone(com,mat,quan,prod,t1):
	time.sleep(180)
	factor = 2.2
	m = ComMat.objects.get(com=com,mat=mat)
	m.amt = m.amt+quan*factor
	m.save()
	com.prod_units = com.prod_units+prod
	com.save()

def addProdReq(request):
	capacity=10
	try:
		com = Company.objects.get(pk=request.POST['com'])
		mat = Material.objects.get(pk=com.com_type.id)
		mat1 = Material.objects.get(pk=request.POST['mat1'])
		mat2 = Material.objects.get(pk=request.POST['mat2'])
	#	pdb.set_trace()
		noMat = Material.objects.all().count()
	#	return HttpResponse(mat1.id%noMat)
		quantity = int(request.POST['quantity'])
		if((mat.id-1)%noMat!= (mat1.id%noMat) and (mat.id-2)%noMat!= (mat1.id%noMat) and (mat.id-3)%noMat!= (mat1.id%noMat) ):
			return HttpResponse("Material 1 input cannot be used to produce output.")
		if((mat.id-1)%noMat != (mat2.id%noMat) and (mat.id-2)%noMat != (mat2.id%noMat) and (mat.id-3)%noMat!= (mat2.id%noMat) ):
			return HttpResponse("Material 2 input cannot be used to produce output.")
		if(mat1.id==mat2.id):
			return HttpResponse("You entered the same material twice")
		m1 = ComMat.objects.get(com=com,mat=mat1) 
		m2 = ComMat.objects.get(com=com,mat=mat2) 
		if(m1.amt<quantity or m2.amt<quantity or quantity > com.prod_units*capacity):
			return HttpResponse("You do not have so many raw materials or production units")
	except (KeyError, Company.DoesNotExist):
		return render(request,'netIITD/index.html',{'error_message':'Selected Choice non-existent',})
	else:
		#reduce mat1,mat2,produnits
		m1.amt = m1.amt - quantity
		m2.amt = m2.amt - quantity
		useProd = math.ceil(quantity/capacity)
		com.prod_units = com.prod_units - useProd
		com.save()
		m1.save()
		m2.save()
		pr = ProdReq(com=com,out=mat,prod_units = useProd)
		pr.save()
		t = threading.Thread(target=prodDone,args=(com,mat,quantity,useProd,time.time()))
		t.start()
		return redirect('/bsp/net/showall')

def purProdHouse(request):
	nat = Nation.objects.get(pk=request.POST['nat'])
	com = Company.objects.get(pk=request.POST['com'])
	ppph = float(request.POST['ppph'])
	numProd = int(request.POST['prodh'])

	if(numProd>nat.prod_units or ppph*numProd>com.com_money):
		return HttpResponse("Either not enough Prod units with the nation or not enough money with the company")
	
	nat.nation_money = nat.nation_money + ppph*numProd
	com.com_money = com.com_money - ppph*numProd
	nat.prod_units = nat.prod_units - numProd
	com.prod_units = com.prod_units + numProd
	pph = PurProdHouse(com=com,nation=nat,prod_units=numProd,price_per_unit=ppph)
	pph.save()
	com.save()
	nat.save()

	return redirect('/bsp/net/showall')

def purBankVeto(request):
	nat = Nation.objects.get(pk=request.POST['nat'])
	bank = Bank.objects.get(pk=request.POST['bank'])
	price = float(request.POST['price'])
	vetoDemand = float(request.POST['veto_demand'])
	bn = BankNation.objects.get(nation=nat,bank=bank)

	if(vetoDemand>bank.veto or price>nat.nation_money):
		return Http.Response("Either not enough  Veto with the bank or not enough money with the nation")
	
	nat.nation_money = nat.nation_money - price
	bank.bank_money = bank.bank_money + price
	bank.veto = bank.veto - vetoDemand
	bn.veto_part = bn.veto_part + vetoDemand
	pbv = PurBankVeto(nation=nat,bank=bank,price=price,veto=vetoDemand)
	pbv.save()
	bn.save()
	bank.save()
	nat.save()
	return redirect('/bsp/net/showall')

def BankLoan(request):
	com = Company.objects.get(pk=request.POST['com'])
	bank = Bank.objects.get(pk=request.POST['bank'])
	loan = float(request.POST['loanamt'])
	interest = float(request.POST['interest'])
	interest = interest/100
	if loan > bank.bank_money:
		return HttpResponse("Not enough money to loan")
	com.com_money = com.com_money + loan
	bank.bank_money = bank.bank_money - loan
	l = LoanTrans(com=com,bank=bank,ret=loan*(1+interest))
	com.save()
	bank.save()
	l.save()
	return redirect('/bsp/net/showall')

def Payback(request):
	loans = LoanTrans.objects.all()
	for l in loans:
		com = l.com
		bank = l.bank
		ret = l.ret
		if(com.com_money<ret):
			ret = com.com_money
		com.com_money = com.com_money-ret
		bank.bank_money = bank.bank_money + ret
		com.save()
		bank.save()
	LoanTrans.objects.all().delete()
	return redirect('/bsp/net/showall')

def RetGov(request):
	coms = Company.objects.all()
	for c in coms:
		mat = c.com_type
		matq = ComMat.objects.get(com=c,mat=mat)
		c.com_money = c.com_money + matq.amt * mat.base_price
		matq.amt=0
		c.save()
		matq.save()
	return redirect('/bsp/net/showall')

#@csrf_exempt
def SaveData(request):
	dbname = request.POST['dbname']
	dbname = "/Users/prakhar0409/random/bspBack/mysite/netIITD/save_"+dbname
	cmd = "sh /Users/prakhar0409/random/bspBack/mysite/netIITD/backup.sh "+dbname
	os.system(cmd)
	di = os.getcwd()
	f = open(dbname)
	outp = f.read()
	f.close()

	return HttpResponse(outp)
	#return HttpResponse(di)
	#return serve(request, os.path.basename(dbname), os.path.dirname(dbname))
	#response = StreamingHttpResponse(outp)
	#response['Content-Type'] = 'text/plain; charset=utf8'
	#return response

def Restart(request):
	companies = Company.objects.all()
	return HttpResponse("Hey buddy")


def Reset(request):
	companies = Company.objects.all()
	materials = Material.objects.all()
	nations = Nation.objects.all()
	banks = Bank.objects.all()

	for c in companies:
		c.prod_units = 1
		c.com_money = 20000.0
		c.save()
	
	for n in nations:
		n.nation_money = 100000
		n.prod_units = 3
		n.save()

	for b in banks:
		b.bank_money = 1500000
		b.veto = 100
		b.save()

	for n in nations:
		for b in banks:
			bn = BankNation.objects.get(nation=n,bank=b)
			bn.veto_part = 0;
			bn.save()

	for c in companies:
		for m in materials:
			cm = ComMat.objects.get(com=c,mat=m)
			if c.com_type.id == m.id:
				cm.amt = 30.0
			else:
				cm.amt = 0.0
			cm.save()
	
	LoanTrans.objects.all().delete()
	ProdReq.objects.all().delete()
	ProdTrans.objects.all().delete()
	PurProdHouse.objects.all().delete()
#	PurBankVeto.objects.all().delete()

	#cmd = "./reset.sh"
	#os.system(cmd)
	return redirect('/bsp/net/showall')

mysite/netIITD/templates/netIITD/base.html
<head>
	<title>NET IITD</title>

<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

</head>

mysite/netIITD/templates/netIITD/index.html
{% include "netIITD/base.html" %}
<style>
body{
	font-family:"Comic Sans MS","sans-serif";
}
div div{
	margin-right:5%;
}
body > div{
	background-color:#ddf;
}
h1,h2,h3{
	text-align:center;
}
h2{
	text-decoration:underline;
}
</style>
<body>
<h1>Negotiation Table, IIT Delhi 2016</h1>

<h2>Companies Status</h2>
{% if companies %}
	<table class="table table-striped">
		<thead class="thead-inverse">
			<tr class="bg-primary">
				<th>Companyname</th>
				<th>IndustryType</th>
				{% for m in materials %}
				<th>{{ m.material_name }}</th>
				{% endfor %}
				<th>Produtionunits</th>
				<th>Money</th>
			</tr>
		</thead>
		<tbody>
		{% for c in companies %}
		<tr>
			{% comment %}
			{% for a in c._meta.get_fields() %}
			<td>{{ getattr(c,a,None) }}</td>
			{% endfor %}
			{% endcomment %}
			
			<td>{{ c.com_name }}</td>
			<td>{{ c.com_type }}</td>
			{% for cm in commats %}
			{% if c.id == cm.com.id %}
			<td>{{ cm.amt }}</td>
			{% endif %}
			{% endfor %}
			<td>{{ c.prod_units }}</td>
			<td>{{ c.com_money }}</td>
		</tr>
		{% endfor %}
	</tbody>
	</table>

	
	<h2>Industry type vs Raw materials</h2>	
	<table class="table table-striped">
		<thead class="thead-inverse">
			<tr class="bg-info">
			<th>Industry type</th>
			<th>Raw1</th>
			<th>Raw2</th>
			<th>Raw3</th>
		</tr>
	</thead>
	<tbody>
		{% for m in mx %}
		<tr>	
			{% for m1 in m %}
			<td>{{ m1.material_name }}</td>
			{% endfor %}
		</tr>
		{% endfor %}
	</tbody>
	</table>
	

{% else %}
	<p>No companies have been added yet!</p>
{% endif %}


<h3>Add a transaction between two Companies:</h3>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<div>
<form action="{% url 'netIITD:comtrans' %}" method="post">
	{% csrf_token %}
	<div style="float:left;">
		From Company:<br/>
		<select name="c1">
		{% for c in companies %}
		<option value="{{ c.id }}">{{ c.com_name }}</option>
		{% endfor %}
		</select>
	</div>
	<div style="float:left; ">
		To Company:<br/>
		<select name="c2">
		{% for c in companies %}
		<option value="{{ c.id }}">{{ c.com_name }}</option>
		{% endfor %}
		</select>
	</div>
	{% comment %}
	<div style="float:left;">
		From Company:<br/>
		{% for c in companies %}
		<input type='radio' name='c1' id='c{{ forloop.counter }}' value="{{ c.id }}"/>
		<label for="com{{ forloop.counter }}">{{ c.com_name }} </label><br/>
		{% endfor %}
	</div>
	<div style="float:left; ">
		To Company: <br/>
		{% for c in companies %}
		<input type='radio' name='c2' id='c{{ forloop.counter }}' value="{{ c.id }}"/>
		<label for="com{{ forloop.counter }}">{{ c.com_name }} </label><br/>
		{% endfor %}
	</div>
	{% endcomment %}
	<div style='float:left;'>
		Material:<br/>
		<select name='mat'>
			{% for m in materials %}
			<option value='{{ m.id }}'>{{ m.material_name }}</option>
			{% endfor %}
		</select>
	</div>
	<div style='float:left;'>
		Price per unit:<br/> <input type="number" name="ppu" value="0"><br>
	</div>
	<div style='float:left;'>
		Units <br/><input type="number" name="units" value="0"><br/>
	</div>
	<br/>
	<input type='submit' value='Add Transaction'>
</form>
</div>


<hr/>
<h3>Production Request:</h3>

<div>
<form action="{% url 'netIITD:prodreq' %}" method="post">
	{% csrf_token %}
	<div style="float:left; ">
		From Company:<br/>
		<select name="com">
		{% for c in companies %}
		<option value="{{ c.id }}">{{ c.com_name }}</option>
		{% endfor %}
		</select>
	</div>

	<div style='float:left;'>
		Material 1:<br/>
		<select name='mat1'>
			{% for m in materials %}
			<option value="{{ m.id }}">{{ m.material_name }}</option>
			{% endfor %}
		</select>
	</div>
	<div style='float:left;'>
		Material 2:<br/>
		<select name='mat2'>
			{% for m in materials %}
			<option value="{{ m.id }}">{{ m.material_name }}</option>
			{% endfor %}	
		</select>
	</div>
	<div style='float:left;'>
		Quantity:<br/> <input type="number" name="quantity" value="0"><br>
	</div>
	<br/>
	<input type='submit' value='Add Production Request'>
</form>
</div>

<br/>
<hr/>
<h2>Banks</h2>
<table class="table table-striped">
	<thead class="thead-inverse">
		<tr class="bg-primary">
		<th>Bank Name</th>
		<th>Money</th>
		<th>Veto Percent</th>
	</tr>
</thead>
<tbody>
	{% for b in banks %}
	<tr>
		<td>{{ b.bank_name }}</td>
		<td>{{ b.bank_money }}</td>
		<td>{{ b.veto }}</td>
	</tr>
	{% endfor %}
</tbody>
</table>

<h3>Purchase bank shares(veto percent):</h3>

<div>
<form action="{% url 'netIITD:purbankveto' %}" method="post">
	{% csrf_token %}
	<div style="float:left;">
		From Bank:<br/>
		<select name="bank">
		{% for b in banks %}
		<option value="{{ b.id }}">{{ b.bank_name }}</option>
		{% endfor %}
		</select>
	</div>

	<div style='float:left;'>
		To Nation:<br/>
		<select name='nat'>
			{% for n in nations %}
			<option value="{{ n.id }}">{{ n.nation_name }}</option>
			{% endfor %}
		</select>
	</div>
	<div style='float:left;'>
		Percentage demanded:<br/> <input type="number" name="veto_demand" value="0"><br>
	</div>
	<div style='float:left;'>
		Deal Price:<br/> <input type="number" name="price" value="0"><br>
	</div>
	<br/>
	<input type='submit' value='Buy Bank Veto'>
</form>
</div>
<hr/>
<h3>Bank Loans:</h3>

<div>
<form action="{% url 'netIITD:bankloan' %}" method="post">
	{% csrf_token %}
	<div style="float:left;">
		From Bank:<br/>
		<select name="bank">
		{% for b in banks %}
		<option value="{{ b.id }}">{{ b.bank_name }}</option>
		{% endfor %}
		</select>
	</div>

	<div style='float:left;'>
		To Company:<br/>
		<select name='com'>
			{% for c in companies %}
			<option value="{{ c.id }}">{{ c.com_name }}</option>
			{% endfor %}
		</select>
	</div>
	<div style='float:left;'>
		Loan Amt:<br/> <input type="number" name="loanamt" value="0"><br>
	</div>
	<div style='float:left;'>
		Interest:<br/> <input type="number" name="interest" value="0"><br>
	</div>
	<br/>
	<input type='submit' value='Give Loan'>
</form>
</div>
<br/>
<hr/>
<h2>Nations</h2>
<table class="table table-striped">
	<thead class="thead-inverse">
		<tr class="bg-primary">
		<th>Name</th>
		<th>Money</th>
		<th>Production Houses</th>
		{% for b in banks %}
		<th>{{ b.bank_name }}</th>
		{% endfor %}
	</tr>
	</thead>
	<tbody>
	{% for n in nations %}
	<tr>
		<td>{{ n.nation_name }}</td>
		<td>{{ n.nation_money }}</td>
		<td>{{ n.prod_units }}</td>
		{% for idx in bankNo %}
			{% for bn in banknations %}
				{% if bn.nation.id == n.id and bn.bank.id == idx %}
				<td>{{ bn.veto_part }}</td>
				{% endif %}
			{% endfor %}
		{% endfor %}

	</tr>
</tbody>
	{% endfor %}
</table>
<br/>
<h3>Production House Purchase:</h3>

<div>
<form action="{% url 'netIITD:prodhpur' %}" method="post">
	{% csrf_token %}
	<div style="float:left;">
		From Nation:<br/>
		<select name="nat">
		{% for n in nations %}
		<option value="{{ n.id }}">{{ n.nation_name }}</option>
		{% endfor %}
		</select>
	</div>

	<div style='float:left;'>
		To Company:<br/>
		<select name='com'>
			{% for c in companies %}
			<option value="{{ c.id }}">{{ c.com_name }}</option>
			{% endfor %}
		</select>
	</div>
	<div style='float:left;'>
		# of Prod houses:<br/> <input type="number" name="prodh" value="0"><br>
	</div>
	<div style='float:left;'>
		Price per Prod house:<br/> <input type="number" name="ppph" value="0"><br>
	</div>
	<br/>
	<input type='submit' value='Buy Prod House'>
</form>
</div>

<br/>
<hr/>
<h2>Game Options:</h2>
<form action="{% url 'netIITD:payback' %}" method="post">
	{% csrf_token %}
	    <input type="submit" value="Payback (Companies pay back Loans)" />
</form>
<form action="{% url 'netIITD:retgov' %}" method="post">
	{% csrf_token %}
	    <input type="submit" value="Return to Gov (Companies sell their identity product to Gov at base price)" />
    </form>

    {% comment %}
<form action="{% url 'netIITD:savedata' %}" method="post">
	{% csrf_token %}
	DB File name (db1.json,db2.json etc recommended)
	<input type='text' name='dbname'>
	<input type="submit" value="Save Data to a file (Recommended before you reset)" />
</form>
<form action="{% url 'netIITD:reset' %}" method="post">
	{% csrf_token %}
	    <input type="submit" value="Reset Game" />
</form>
    {% endcomment %}
</body>
</html>

mysite/netIITD/templates/netIITD/tp.html
{% include "netIITD/base.html" %}
<table class="table">
  <thead class="thead-inverse">
    <tr class="bg-primary">
      <th>#</th>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Username</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row">1</th>
      <td>Mark</td>
      <td>Otto</td>
      <td>@mdo</td>
    </tr>
    <tr>
      <th scope="row">2</th>
      <td>Jacob</td>
      <td>Thornton</td>
      <td>@fat</td>
    </tr>
    <tr>
      <th scope="row">3</th>
      <td>Larry</td>
      <td>the Bird</td>
      <td>@twitter</td>
    </tr>
  </tbody>
</table>

<table class="table">
  <thead class="thead-default">
    <tr>
      <th>#</th>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Username</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row">1</th>
      <td>Mark</td>
      <td>Otto</td>
      <td>@mdo</td>
    </tr>
    <tr>
      <th scope="row">2</th>
      <td>Jacob</td>
      <td>Thornton</td>
      <td>@fat</td>
    </tr>
    <tr>
      <th scope="row">3</th>
      <td>Larry</td>
      <td>the Bird</td>
      <td>@twitter</td>
    </tr>
  </tbody>
</table>